CREATE FUNCTION fn_Formato_hora (@TEMPO INT, @FORMATO INT)

RETURNS VARCHAR(20)

AS

BEGIN

DECLARE @HORARIO VARCHAR(20)

DECLARE @HORA INT

DECLARE @MINUTO INT

DECLARE @SEGUNDO INT

DECLARE @NEGATIVO BOOLEAN

SET @NEGATIVO = 0 -- VARIÁVEL @NEGATIVO PARA CONTROLE DE RESULTADOS NEGATIVOS.

IF @TEMPO < 0 -- TESTA SE A VARIÁVEL DE ENTRADA É NEGATIVA.

BEGIN

SET @TEMPO = @TEMPO * -1; -- CONVERTE A VARIÁVEL DE ENTRADA EM POSITIVO.

SET @NEGATIVO = 1 -- ALTERA O STATUS DA VARIÁVEL DE CONTROLE.

END

--FORMATO DE HH:MM:SS

IF @FORMATO = 1

BEGIN

SET @HORA = (@TEMPO/3600)

SET @MINUTO = (@TEMPO%3600) / 60

SET @SEGUNDO = (@TEMPO%3600) % 60

SELECT @HORARIO =

CASE WHEN @TEMPO/3600 >= 1

THEN CASE LEN(CAST((@HORA) AS VARCHAR)) WHEN 1

THEN '0'

ELSE ''

END + CAST ((@HORA) AS VARCHAR) + ':' + CASE LEN(CAST((@MINUTO) AS VARCHAR)) WHEN 1

THEN '0'

ELSE ''

END + CAST((@MINUTO) AS VARCHAR) + ':' + CASE LEN(CAST((@SEGUNDO) AS VARCHAR)) WHEN 1

THEN '0'

ELSE ''

END + CAST((@SEGUNDO) AS VARCHAR)

ELSE CASE LEN(CAST((@MINUTO) AS VARCHAR)) WHEN 1

THEN '0'

ELSE ''

END + CAST((@MINUTO) AS VARCHAR) + ':' + CASE LEN(CAST((@SEGUNDO) AS VARCHAR)) WHEN 1

THEN '0'

ELSE ''

END + CAST((@SEGUNDO) AS VARCHAR)

END

END

--FORMATO DE HH:MM

ELSE IF @FORMATO = 2

BEGIN

SET @HORA = (@TEMPO/60)

SET @MINUTO = (@TEMPO%60)

SELECT @HORARIO =

CASE LEN(CAST((@HORA) AS VARCHAR)) WHEN 1

THEN '0'

ELSE ''

END + CAST ((@HORA) AS VARCHAR) + ':' + CASE LEN(CAST((@MINUTO) AS VARCHAR)) WHEN 1 THEN '0' ELSE '' END + CAST((@MINUTO) AS VARCHAR)

END

--TRATA O RESULTADO NEGATIVO

IF @NEGATIVO = 1

SET @HORARIO = ('-' + @HORARIO)

RETURN (@HORARIO)

END

Completion time: 2023-11-23T14:56:04.7451923-03:00
